import type { Metadata } from "next";
import Link from "next/link";
import { ProsePage, Section, Bullets } from "@/components/marketing/prose-page";

export const metadata: Metadata = {
  title: "Terms · Nexora",
  description: "The terms of use for Nexora: free, as-is, and yours to verify.",
};

export default function TermsPage() {
  return (
    <ProsePage
      eyebrow="Terms"
      title="Terms of use"
      intro="Nexora is free software with no payment and an optional account. These terms are correspondingly short."
      updated="4 August 2026"
    >
      <Section title="Using Nexora">
        <p>
          You may use Nexora for any lawful purpose, personal or commercial, at no cost. There is no
          licence to accept, no seat to buy, and no usage to report. Because the workspace runs on
          your device, using it creates no relationship between us beyond your visiting this site.
        </p>
      </Section>

      <Section title="Your data and your outputs">
        <p>
          Your files, and everything Nexora produces from them, belong to you. No claim is made over
          any dataset, chart, report, or export you create here. You are responsible for having the
          right to work with the data you load.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          Nexora is provided as-is, without warranty of any kind. Its analysis is generated by rules
          documented in the{" "}
          <Link href="/docs" className="text-primary hover:underline">documentation</Link>, and those
          rules are heuristics, not certainties.
        </p>
        <Bullets
          items={[
            "Column meanings are inferred from names and distributions and can be inferred wrongly.",
            "Outlier detection uses the 1.5×IQR convention, which flags legitimate extremes in skewed data.",
            "Cleaning suggestions are suggestions. Each one previews its effect and each one is undoable, because you are the one deciding.",
            "Check anything that matters before it becomes a decision. This is true of every analytics tool; it is stated plainly here because the reports read as though they were written by an analyst.",
          ]}
        />
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, no liability is accepted for any loss arising from
          your use of Nexora, including decisions taken on the basis of its output or any loss of
          data held in your browser&apos;s storage. Local storage can be cleared by your browser
          without warning; keep exports of anything you cannot afford to lose.
        </p>
      </Section>

      <Section title="Availability">
        <p>
          A deployment of this site may be moved, changed, or taken down at any time. The source is
          on{" "}
          <a
            href="https://github.com/Ghostiemoh/nexora"
            target="_blank"
            rel="noreferrer noopener"
            className="text-primary hover:underline"
          >
            GitHub
          </a>
          , so nothing here is a dependency you cannot run yourself.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          Revisions will be dated at the top of this page and noted in the{" "}
          <Link href="/changelog" className="text-primary hover:underline">changelog</Link>.
        </p>
      </Section>
    </ProsePage>
  );
}
